languageCode = 'pt-br'
baseURL = '/'
title = 'Riflett'
theme = "paper"
disqusShortname = 'riflett'   # add disqus comments
categories = ['filosofia']
summaryLength = 15
googleAnalytics = 'G-YBHL7RLVJ4'

[menu]
[[menu.main]]
  identifier = 'privacy-policy'
  name = 'Privacidade'
  url = '/privacy-policy/'
[[menu.footer]]
  identifier = 'privacy-policy'
  name = 'Privacidade'
  url = '/privacy-policy/'

[[module.mounts]]
  source = 'assets'
  target = 'assets'

[taxonomies]
  category = 'categories'

[params]
  # color style
  color = 'linen'                   # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'       # twitter.com/YOUR_TWITTER_ID
  # github = 'YOUR_GITHUB_ID'         # github.com/YOUR_GITHUB_ID
  instagram = 'riflett_'   # instagram.com/YOUR_INSTAGRAM_ID
  # mastodon = 'YOUR_MASTODON_LINK'   # e.g. 'https://mastodon.instance/@xxx'
  rss = true                        # show rss icon

  # home page profile
  # avatar = 'GRAVATAR_EMAIL'         # Gravatar email or image url
  name = 'Guilherme Isaías'
  # bio = 'YOUR_BIO'

  # misc
  disableHLJS = true                # disable requesting highlight.js
  monoDarkIcon = true               # show monochrome dark mode icon
  # gravatarCdn = 'GRAVATAR_CDN_LINK' # e.g. 'https://cdn.v2ex.com/gravatar/'
  googleAdsense = 'ca-pub-5178116163420045'
  description = 'Artigos sobre ciência, filosofia, política, tecnologia, e outros assuntos, de uma forma cética e pragmática.'
